[tools]
deno = "latest"

[tasks.start]
description = "Start main task"
run = "deno task run"

[tasks.test]
description = "Run tests"
run = "deno task test"

[tasks.fmt]
description = "Format code"
run = "deno fmt"
